"""initial_schema

Revision ID: 95208d5f6108
Revises: 
Create Date: 2026-05-30 08:06:03.720372
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '95208d5f6108'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    op.create_table('permissions',
    sa.Column('resource', sa.String(length=100), nullable=False, comment='Resource: users, tenants, workflows, clinical, audit, agents, settings'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='Action: create, read, update, delete, execute, export'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Optional conditions: e.g., {own_records_only: true}'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource', 'action', name='uq_permission_resource_action')
    )
    op.create_index(op.f('ix_permissions_is_deleted'), 'permissions', ['is_deleted'], unique=False)
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('subscription_tier', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Tenant configuration: HIS systems, language defaults, compliance region, etc.'),
    sa.Column('compliance_region', sa.String(length=50), nullable=False, comment='Data residency: us, eu, in, ae, uk, sg'),
    sa.Column('admin_email', sa.String(length=255), nullable=True),
    sa.Column('admin_phone', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_is_deleted'), 'tenants', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('translation_cache',
    sa.Column('source_lang', sa.String(length=10), nullable=False),
    sa.Column('target_lang', sa.String(length=10), nullable=False),
    sa.Column('source_text_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash of source text'),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_cache_is_deleted'), 'translation_cache', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_translation_cache_source_lang'), 'translation_cache', ['source_lang'], unique=False)
    op.create_index(op.f('ix_translation_cache_source_text_hash'), 'translation_cache', ['source_text_hash'], unique=False)
    op.create_index(op.f('ix_translation_cache_target_lang'), 'translation_cache', ['target_lang'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True, comment='User who performed the action (null for system actions)'),
    sa.Column('agent_session_id', sa.UUID(), nullable=True, comment='Agent session if action was performed by an agent'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='Action: create, read, update, delete, login, logout, execute, approve, reject, export'),
    sa.Column('action_category', sa.String(length=50), nullable=False, comment='Category: auth, clinical, workflow, admin, agent, compliance'),
    sa.Column('resource_type', sa.String(length=100), nullable=False, comment='Resource: user, tenant, workflow, clinical_note, agent_session, etc.'),
    sa.Column('resource_id', sa.String(length=100), nullable=True, comment='ID of the affected resource'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional details (PHI-free)'),
    sa.Column('previous_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='State before change (for update/delete)'),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('integrity_hash', sa.String(length=64), nullable=False, comment='SHA-256 chain hash for tamper detection'),
    sa.Column('previous_hash', sa.String(length=64), nullable=False, comment='Hash of the previous audit log entry'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('screenshot_url', sa.String(length=500), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='Severity: info, warning, critical'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_agent_session_id'), 'audit_logs', ['agent_session_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_is_deleted'), 'audit_logs', ['is_deleted'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index('ix_audit_logs_tenant_timestamp', 'audit_logs', ['tenant_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_logs_user_action', 'audit_logs', ['user_id', 'action'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('his_targets',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('his_type', sa.String(length=50), nullable=False, comment='Type: web, desktop, hybrid'),
    sa.Column('base_url', sa.String(length=500), nullable=True, comment='Base URL for web-based HIS'),
    sa.Column('application_path', sa.String(length=500), nullable=True, comment='Executable path for desktop HIS'),
    sa.Column('auth_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Encrypted auth config: {type, username_encrypted, password_encrypted, ...}'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Status: pending, active, inactive, error'),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_check_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('browser_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Playwright config: viewport, user_agent, proxy, etc.'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_his_targets_is_deleted'), 'his_targets', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_his_targets_tenant_id'), 'his_targets', ['tenant_id'], unique=False)
    op.create_table('language_configs',
    sa.Column('language_code', sa.String(length=10), nullable=False, comment='ISO 639-1/639-3 code: en, hi, ar, ms, sw, etc.'),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('native_name', sa.String(length=100), nullable=True, comment='Name in the language itself: हिन्दी, العربية'),
    sa.Column('is_rtl', sa.Boolean(), nullable=False, comment='Right-to-left language: Arabic, Hebrew, Urdu'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('stt_model', sa.String(length=100), nullable=False, comment='STT model: whisper-large-v3, google-stt-v2, azure-cognitive'),
    sa.Column('stt_accuracy_target', sa.Float(), nullable=False, comment='Target WER accuracy'),
    sa.Column('tts_voice', sa.String(length=100), nullable=True, comment='TTS voice ID'),
    sa.Column('tts_model', sa.String(length=100), nullable=False),
    sa.Column('translation_model', sa.String(length=100), nullable=False, comment='Translation model: indictrans2, opus-mt, google-translate'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_configs_is_deleted'), 'language_configs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_language_configs_language_code'), 'language_configs', ['language_code'], unique=False)
    op.create_index(op.f('ix_language_configs_tenant_id'), 'language_configs', ['tenant_id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False, comment='System roles are immutable and cannot be deleted'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Higher priority = more access. Used for role hierarchy.'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_role_tenant_name')
    )
    op.create_index(op.f('ix_roles_is_deleted'), 'roles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True, comment='Job title: Dr., Nurse, Admin, etc.'),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True, comment='Encrypted TOTP secret'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language_preference', sa.String(length=10), nullable=False),
    sa.Column('theme_preference', sa.String(length=20), nullable=False, comment='Theme: light, dark, system'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('his_element_maps',
    sa.Column('his_target_id', sa.UUID(), nullable=False),
    sa.Column('element_name', sa.String(length=255), nullable=False, comment="Human-readable element name: 'Patient Name Input', 'Save Button'"),
    sa.Column('element_type', sa.String(length=50), nullable=False, comment='Type: input, button, link, select, table, text, container'),
    sa.Column('page_context', sa.String(length=255), nullable=True, comment='Page/screen where this element appears'),
    sa.Column('selectors', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Selectors: {accessibility: ..., css: ..., xpath: ..., text: ..., visual: ...}'),
    sa.Column('last_verified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_screenshot_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['his_target_id'], ['his_targets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_his_element_maps_his_target_id'), 'his_element_maps', ['his_target_id'], unique=False)
    op.create_index(op.f('ix_his_element_maps_is_deleted'), 'his_element_maps', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_his_element_maps_tenant_id'), 'his_element_maps', ['tenant_id'], unique=False)
    op.create_table('patient_encounters',
    sa.Column('encounter_id_encrypted', sa.Text(), nullable=False, comment='AES-256 encrypted encounter ID from HIS'),
    sa.Column('patient_id_encrypted', sa.Text(), nullable=False, comment='AES-256 encrypted patient identifier from HIS'),
    sa.Column('patient_name_encrypted', sa.Text(), nullable=True, comment='AES-256 encrypted patient name'),
    sa.Column('clinician_id', sa.UUID(), nullable=True),
    sa.Column('encounter_type', sa.String(length=50), nullable=False, comment='Type: outpatient, inpatient, emergency, telehealth'),
    sa.Column('encounter_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Status: active, completed, cancelled'),
    sa.Column('his_source', sa.String(length=255), nullable=True, comment='HIS system where this encounter originated'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_encounters_is_deleted'), 'patient_encounters', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_patient_encounters_tenant_id'), 'patient_encounters', ['tenant_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_is_deleted'), 'role_permissions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_index(op.f('ix_user_roles_is_deleted'), 'user_roles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('workflow_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False, comment='Category: clinical, administrative, billing, registration, reporting'),
    sa.Column('his_target_id', sa.UUID(), nullable=True),
    sa.Column('mode', sa.String(length=50), nullable=False, comment='Mode: assisted (human confirms), automated (runs autonomously)'),
    sa.Column('risk_level', sa.String(length=20), nullable=False, comment='Risk: low, medium, high, critical'),
    sa.Column('steps_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Ordered list of workflow step configurations'),
    sa.Column('trigger_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Trigger: manual, scheduled, event-based'),
    sa.Column('retry_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{"max_retries": 3, "backoff_seconds": 5}', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['his_target_id'], ['his_targets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_templates_is_deleted'), 'workflow_templates', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_workflow_templates_tenant_id'), 'workflow_templates', ['tenant_id'], unique=False)
    op.create_table('clinical_notes',
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=False, comment='Type: progress, admission, discharge, consultation, procedure'),
    sa.Column('content_encrypted', sa.Text(), nullable=False, comment='AES-256 encrypted note content'),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('is_transcribed', sa.Boolean(), nullable=False),
    sa.Column('transcription_source', sa.String(length=50), nullable=True, comment='Source: manual, whisper_stt, voice_recording'),
    sa.Column('is_coded', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['patient_encounters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_notes_encounter_id'), 'clinical_notes', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_clinical_notes_is_deleted'), 'clinical_notes', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_clinical_notes_tenant_id'), 'clinical_notes', ['tenant_id'], unique=False)
    op.create_table('soap_notes',
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('subjective_encrypted', sa.Text(), nullable=True),
    sa.Column('objective_encrypted', sa.Text(), nullable=True),
    sa.Column('assessment_encrypted', sa.Text(), nullable=True),
    sa.Column('plan_encrypted', sa.Text(), nullable=True),
    sa.Column('icd_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of ICD-10 codes extracted'),
    sa.Column('snomed_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of SNOMED CT codes extracted'),
    sa.Column('loinc_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of LOINC codes for lab/observations'),
    sa.Column('generated_by', sa.String(length=50), nullable=False, comment='Source: manual, ai_structured, voice_transcription'),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('llm_model_used', sa.String(length=100), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['patient_encounters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soap_notes_encounter_id'), 'soap_notes', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_soap_notes_is_deleted'), 'soap_notes', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_soap_notes_tenant_id'), 'soap_notes', ['tenant_id'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('initiated_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Status: pending, running, paused, completed, failed, aborted'),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('agent_session_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_is_deleted'), 'workflow_executions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_workflow_executions_status'), 'workflow_executions', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_executions_template_id'), 'workflow_executions', ['template_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_tenant_id'), 'workflow_executions', ['tenant_id'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False, comment='Type: navigate, click, fill, extract, validate, wait, screenshot, conditional'),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Step-specific parameters'),
    sa.Column('requires_confirmation', sa.Boolean(), nullable=False, comment='If true, agent pauses and waits for human confirmation'),
    sa.Column('confirmation_message', sa.Text(), nullable=True, comment='Message shown to human during confirmation'),
    sa.Column('on_failure', sa.String(length=50), nullable=False, comment='Failure action: abort, retry, skip, fallback'),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_steps_is_deleted'), 'workflow_steps', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_workflow_steps_template_id'), 'workflow_steps', ['template_id'], unique=False)
    op.create_index(op.f('ix_workflow_steps_tenant_id'), 'workflow_steps', ['tenant_id'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('workflow_execution_id', sa.UUID(), nullable=True),
    sa.Column('his_target_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Status: initializing, active, paused, waiting_confirmation, completed, failed, aborted'),
    sa.Column('mode', sa.String(length=50), nullable=False, comment='Mode: assisted, automated'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('browser_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Current browser state: url, page_title, viewport'),
    sa.Column('total_actions', sa.Integer(), nullable=False),
    sa.Column('successful_actions', sa.Integer(), nullable=False),
    sa.Column('failed_actions', sa.Integer(), nullable=False),
    sa.Column('human_interventions', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['his_target_id'], ['his_targets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_sessions_is_deleted'), 'agent_sessions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_agent_sessions_status'), 'agent_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_agent_sessions_tenant_id'), 'agent_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_user_id'), 'agent_sessions', ['user_id'], unique=False)
    op.create_table('coded_entities',
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='Type: diagnosis, medication, allergy, procedure, vital, symptom, lab_result'),
    sa.Column('text_encrypted', sa.Text(), nullable=False, comment='AES-256 encrypted original text'),
    sa.Column('normalized_text', sa.String(length=500), nullable=True, comment='Normalized/standardized text (non-PHI)'),
    sa.Column('code_system', sa.String(length=50), nullable=True, comment='System: ICD-10, SNOMED-CT, LOINC, RxNorm, NDC'),
    sa.Column('code_value', sa.String(length=50), nullable=True),
    sa.Column('code_display', sa.String(length=500), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=False, comment='Method: nlp, manual, rule_based'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['clinical_notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coded_entities_is_deleted'), 'coded_entities', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_coded_entities_note_id'), 'coded_entities', ['note_id'], unique=False)
    op.create_index(op.f('ix_coded_entities_tenant_id'), 'coded_entities', ['tenant_id'], unique=False)
    op.create_table('agent_actions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False, comment='Type: navigate, click, fill, extract, screenshot, validate, wait'),
    sa.Column('action_description', sa.Text(), nullable=True, comment='Human-readable description of the action'),
    sa.Column('target_element', sa.String(length=255), nullable=True, comment='Element being interacted with'),
    sa.Column('target_selector', sa.Text(), nullable=True, comment='CSS/XPath selector used'),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Action result/extracted data'),
    sa.Column('result_status', sa.String(length=50), nullable=False, comment='Status: pending, success, failure, skipped'),
    sa.Column('screenshot_before_url', sa.String(length=500), nullable=True),
    sa.Column('screenshot_after_url', sa.String(length=500), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True, comment='AI confidence in this action (0.0 - 1.0)'),
    sa.Column('requires_human_approval', sa.Boolean(), nullable=False),
    sa.Column('human_decision', sa.String(length=50), nullable=True, comment='Decision: approved, modified, rejected, null (pending/not required)'),
    sa.Column('human_decision_by', sa.UUID(), nullable=True),
    sa.Column('human_decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('human_modification', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='If modified, what changes the human made'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_actions_is_deleted'), 'agent_actions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_agent_actions_session_id'), 'agent_actions', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_actions_tenant_id'), 'agent_actions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_actions_tenant_id'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_session_id'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_is_deleted'), table_name='agent_actions')
    op.drop_table('agent_actions')
    op.drop_index(op.f('ix_coded_entities_tenant_id'), table_name='coded_entities')
    op.drop_index(op.f('ix_coded_entities_note_id'), table_name='coded_entities')
    op.drop_index(op.f('ix_coded_entities_is_deleted'), table_name='coded_entities')
    op.drop_table('coded_entities')
    op.drop_index(op.f('ix_agent_sessions_user_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_tenant_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_status'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_is_deleted'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_index(op.f('ix_workflow_steps_tenant_id'), table_name='workflow_steps')
    op.drop_index(op.f('ix_workflow_steps_template_id'), table_name='workflow_steps')
    op.drop_index(op.f('ix_workflow_steps_is_deleted'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index(op.f('ix_workflow_executions_tenant_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_template_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_status'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_is_deleted'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_soap_notes_tenant_id'), table_name='soap_notes')
    op.drop_index(op.f('ix_soap_notes_is_deleted'), table_name='soap_notes')
    op.drop_index(op.f('ix_soap_notes_encounter_id'), table_name='soap_notes')
    op.drop_table('soap_notes')
    op.drop_index(op.f('ix_clinical_notes_tenant_id'), table_name='clinical_notes')
    op.drop_index(op.f('ix_clinical_notes_is_deleted'), table_name='clinical_notes')
    op.drop_index(op.f('ix_clinical_notes_encounter_id'), table_name='clinical_notes')
    op.drop_table('clinical_notes')
    op.drop_index(op.f('ix_workflow_templates_tenant_id'), table_name='workflow_templates')
    op.drop_index(op.f('ix_workflow_templates_is_deleted'), table_name='workflow_templates')
    op.drop_table('workflow_templates')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_is_deleted'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_is_deleted'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_patient_encounters_tenant_id'), table_name='patient_encounters')
    op.drop_index(op.f('ix_patient_encounters_is_deleted'), table_name='patient_encounters')
    op.drop_table('patient_encounters')
    op.drop_index(op.f('ix_his_element_maps_tenant_id'), table_name='his_element_maps')
    op.drop_index(op.f('ix_his_element_maps_is_deleted'), table_name='his_element_maps')
    op.drop_index(op.f('ix_his_element_maps_his_target_id'), table_name='his_element_maps')
    op.drop_table('his_element_maps')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_is_deleted'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_language_configs_tenant_id'), table_name='language_configs')
    op.drop_index(op.f('ix_language_configs_language_code'), table_name='language_configs')
    op.drop_index(op.f('ix_language_configs_is_deleted'), table_name='language_configs')
    op.drop_table('language_configs')
    op.drop_index(op.f('ix_his_targets_tenant_id'), table_name='his_targets')
    op.drop_index(op.f('ix_his_targets_is_deleted'), table_name='his_targets')
    op.drop_table('his_targets')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_action', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_tenant_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_is_deleted'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_agent_session_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_translation_cache_target_lang'), table_name='translation_cache')
    op.drop_index(op.f('ix_translation_cache_source_text_hash'), table_name='translation_cache')
    op.drop_index(op.f('ix_translation_cache_source_lang'), table_name='translation_cache')
    op.drop_index(op.f('ix_translation_cache_is_deleted'), table_name='translation_cache')
    op.drop_table('translation_cache')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_is_deleted'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_permissions_is_deleted'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
